const hazards=[
'Lantai Licin','Pekerjaan di atas kepala','Orang Masuk Tanpa Izin','Terhantam Benda','Bahaya Kebakaran','Gas','Gelap (Malam)','Lantai yang berlubang','Percikan Palu','Jepit/Perangkap','Cuaca Buruk','Tepian bangunan','Jalan darurat','Bahaya Cedera Tulang Belakang','Ergonomik','Percikan/Leburan Besi panas','Polusi Alam','Tersandung/Jatuh','Kejatuhan Benda atau Material','Asap','Debu','Salah Penyetelan','Lingkungan yang sesak','Benda Tajam','Kegagalan Peralatan','Keseleo','Beban Berat','Bising','Kegagalan Struktur/Alat Bantu','Ketinggian','Tangga yang tidak Kokoh','Vibrasi/Getaran','Bahan Alat Listrik','Pekerjaan lain yang terdekat','Berangin','Tindakan dari pihak ketiga','Obyek Ayunan','Sambungan sedang (Gas/Tekanan)','Tabrakan/Benturan Benda yang Bergerak','Salah komunikasi','Kereta Melintas','Lain-lain 1','Lain-lain 2','Lain-lain 3'];
const precautions=['Proteksi/Perlindungan Dari Jauh','Rambu-rambu','Pemadam Api/Kebakaran','Body System','Selimut Penghambat Api/Percikan','Penyinaran yang Memadai','Pintu Masuk/Pintu Keluar','Sertifikat Kompetensi','Penyangga','Wajib Mengikuti Penjelasan JSA','Pagar/Barikade/police line','Lain-Lain…..','Handy talkie'];
const ppe=['Helm Keselamatan','Sarung Tangan Kulit','Sepatu Keselamatan','Baju Kulit','Kacamata Keselamatan','Rompi Keselamatan','Perlindungan Muka/Las','Tali Keselamatan','Kacamata Debu','Masker','Sarung Tangan Katun','Pelindung Pendengaran','Sarung Tangan Karet','Lain-lain'];
const completion=['Selesai & diperiksa ,tindakan pencegahan khusus (isolasi,…) telah diambil kembali ,lokasi kerja ditinggalkan dalam keadaaanaman dan bahwa operasional dapat kembali normal','Belum selesai dan akan dilanjutkan dengan izin kerja No….','Tidak terselesaikan dan secara tegas dihentikan','Beberapa langkah harus diambil sebelum operasional dapat berlangsung kembali'];
const $=s=>document.querySelector(s); const $$=s=>[...document.querySelectorAll(s)];
function renderChecks(id, items, name){$(id).innerHTML=items.map((x,i)=>`<label class="check-item"><input type="checkbox" name="${name}" value="${escapeHtml(x)}"><span>${escapeHtml(x)}</span></label>`).join('')}
function renderApprovals(){ $('#approvals').innerHTML=Array.from({length:3},(_,i)=>`<div class="approval-row"><div class="field-title">Baris persetujuan ${i+1}</div><div class="grid two"><label>Penanggung Jawab Izin Kerja<input name="approval${i}Responsible"></label><label>Nama<input name="approval${i}Name"></label><label>Instansi<input name="approval${i}Institution"></label><label>Tanggal<input name="approval${i}Date" type="date"></label><label>Jam<input name="approval${i}Time" type="time"></label><label>Tanda tangan<button type="button" class="signature-open" data-target="approval${i}Signature">Buka kolom tanda tangan</button><input type="hidden" name="approval${i}Signature" id="approval${i}Signature"></label></div></div>`).join('')}
function renderCompletion(){ $('#completion').innerHTML=completion.map((x,i)=>`<label class="check-item"><input type="radio" name="completion" value="${i}"><span>${escapeHtml(x)}</span></label>`).join('')}
function escapeHtml(s){return String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]))}
renderChecks('#hazards',hazards,'hazards');renderChecks('#precautions',precautions,'precautions');renderChecks('#ppe',ppe,'ppe');renderApprovals();renderCompletion();
let activeSig=null; const modal=$('#sigModal'), canvas=$('#sigCanvas'), ctx=canvas.getContext('2d'); let drawing=false;
function pos(e){const r=canvas.getBoundingClientRect();const t=e.touches?.[0]||e;return{x:(t.clientX-r.left)*canvas.width/r.width,y:(t.clientY-r.top)*canvas.height/r.height}}
function start(e){drawing=true;const p=pos(e);ctx.beginPath();ctx.moveTo(p.x,p.y);e.preventDefault()};function move(e){if(!drawing)return;const p=pos(e);ctx.lineTo(p.x,p.y);ctx.stroke();e.preventDefault()};function end(){drawing=false}
canvas.addEventListener('pointerdown',start);canvas.addEventListener('pointermove',move);canvas.addEventListener('pointerup',end);canvas.addEventListener('pointercancel',end);
document.addEventListener('click',e=>{const b=e.target.closest('.signature-open');if(!b)return;activeSig=b.dataset.target;ctx.clearRect(0,0,canvas.width,canvas.height);const old=$('#'+activeSig).value;if(old){const img=new Image();img.onload=()=>ctx.drawImage(img,0,0,canvas.width,canvas.height);img.src=old}modal.classList.remove('hidden')});$('#sigClear').onclick=()=>ctx.clearRect(0,0,canvas.width,canvas.height);$('#sigCancel').onclick=()=>modal.classList.add('hidden');$('#sigUse').onclick=()=>{if(activeSig)$('#'+activeSig).value=canvas.toDataURL('image/png');modal.classList.add('hidden');toast('Tanda tangan disimpan')};
function collect(){const fd=new FormData($('#permitForm'));const o={};for(const [k,v] of fd.entries()){if(k==='workTypes'||k==='equipment'||k==='hazards'||k==='precautions'||k==='ppe') (o[k]??=[]).push(v); else o[k]=v}return o}
function hexToRgb(h){const x=h.replace('#','');return {r:parseInt(x.slice(0,2),16),g:parseInt(x.slice(2,4),16),b:parseInt(x.slice(4,6),16)}}
async function buildPdf(){const data=collect();const {PDFDocument,StandardFonts,rgb}=PDFLib;const out=await PDFDocument.create();const p1=await PDFDocument.load(await fetch('/templates/izin-kerja-1.pdf').then(r=>r.arrayBuffer()));const p2=await PDFDocument.load(await fetch('/templates/izin-kerja-2.pdf').then(r=>r.arrayBuffer()));const [c1]=await out.copyPages(p1,[0]);const [c2]=await out.copyPages(p2,[0]);out.addPage(c1);out.addPage(c2);const font=await out.embedFont(StandardFonts.Helvetica);const bold=await out.embedFont(StandardFonts.HelveticaBold);const black=rgb(0.05,0.05,0.05);
 const text=(page,s,x,y,size=7,opt={})=>{if(!s)return;page.drawText(String(s),{x,y,size,font:opt.bold?bold:font,color:black,maxWidth:opt.maxWidth,lineHeight:size+1})};
 const box=(page,x,y,checked)=>{if(!checked)return;page.drawRectangle({x,y,width:20,height:9,borderColor:rgb(.15,.4,1),borderWidth:1.4,color:rgb(1,1,1)});page.drawText('✓',{x:x+4,y:y+1,size:8,font:bold,color:rgb(.05,.25,.9)})};
 const img=async (page,dataUrl,x,y,w,h)=>{if(!dataUrl)return;const bytes=Uint8Array.from(atob(dataUrl.split(',')[1]),c=>c.charCodeAt(0));const im=await out.embedPng(bytes);page.drawImage(im,{x,y,width:w,height:h})};
 // page 1
 text(c1,data.docCode,520,785,7);text(c1,data.docLevel,520,772,7);text(c1,data.revision,520,759,7);text(c1,data.effectiveStart,520,746,7);text(c1,data.effectiveDate,80,733,7);text(c1,data.permitNo,410,720,7);
 const wt=data.workTypes||[];box(c1,203,708,wt.includes('Kerja Panas'));box(c1,411,708,wt.includes('Ruang Terbatas'));box(c1,550,708,wt.includes('Lain-lain'));
 text(c1,data.region,82,696,7);text(c1,data.applicantName,420,696,7);text(c1,data.location,82,682,7);await img(c1,data.applicantSignature,420,680,90,22);
 text(c1,data.jobDescription,40,645,7,{maxWidth:305});const eq=data.equipment||[];box(c1,347,648,eq.includes('Mesin'));box(c1,347,635,eq.includes('Listrik'));box(c1,347,622,eq.includes('Peralatan Tangan'));
 const cY=[597,584,571,558,545,532,519,506,493,480,467]; const cX=[39,160,300,448]; (data.hazards||[]).forEach(v=>{const i=hazards.indexOf(v);if(i>=0)box(c1,cX[i%4],cY[Math.floor(i/4)],true)});
 const dY=[454,441,428,415,402,389,376]; const dX=[39,299]; (data.precautions||[]).forEach(v=>{const i=precautions.indexOf(v);if(i>=0)box(c1,dX[i%2],dY[Math.floor(i/2)],true)});text(c1,data.otherSafety,150,323,7,{maxWidth:350});
 const eY=[348,335,322,309,296,283,270]; (data.ppe||[]).forEach(v=>{const i=ppe.indexOf(v);if(i>=0)box(c1,[39,299][i%2],eY[Math.floor(i/2)],true)});
 text(c1,data.permissionNote,40,194,7,{maxWidth:500});text(c1,data.fromDate,150,180,7);text(c1,data.fromTime,300,180,7);text(c1,data.issuerName,390,180,7);text(c1,data.toDate,150,167,7);text(c1,data.toTime,300,167,7);text(c1,data.supervisorName,390,167,7);
 // page 2
 text(c2,data.docCode,495,785,7);text(c2,data.docLevel,495,772,7);text(c2,data.revision,495,759,7);text(c2,data.effectiveStart,495,746,7);text(c2,data.effectiveDate,55,733,7);
 for(let i=0;i<3;i++){const y=670-i*32;text(c2,data[`approval${i}Responsible`],15,y,6);text(c2,data[`approval${i}Name`],132,y,6);text(c2,data[`approval${i}Institution`],275,y,6);text(c2,data[`approval${i}Date`],385,y,6);text(c2,data[`approval${i}Time`],468,y,6);await img(c2,data[`approval${i}Signature`],520,y-3,45,16)}
 text(c2,data.cancelReason,15,566,7,{maxWidth:245});text(c2,data.resumeStatement,275,566,7,{maxWidth:255});text(c2,data.cancelDate1,25,532,6);text(c2,data.cancelTime1,115,532,6);text(c2,data.cancelName1,210,532,6);await img(c2,data.cancelSignature1,310,525,65,18);text(c2,data.cancelDate2,405,532,6);text(c2,data.cancelTime2,470,532,6);text(c2,data.cancelName2,520,532,6);await img(c2,data.cancelSignature2,535,525,45,18);
 const comp=Number(data.completion); if(Number.isInteger(comp))box(c2,20,478-comp*13,true);
 text(c2,data.finalResponsible,45,425,6);text(c2,data.finalName,200,425,6);text(c2,data.finalInstitution,340,425,6);text(c2,data.finalDate,415,425,6);text(c2,data.finalTime,505,425,6);await img(c2,data.finalSignature,520,400,55,18);
 return {bytes:await out.save(),data};}
function toast(s){const t=$('#toast');t.textContent=s;t.classList.add('show');setTimeout(()=>t.classList.remove('show'),2800)}
async function downloadPdf(){try{toast('Membuat PDF…');const {bytes}=await buildPdf();const blob=new Blob([bytes],{type:'application/pdf'});const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=`izin-kerja-${collect().permitNo||'baru'}.pdf`;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000);toast('PDF berhasil dibuat')}catch(e){console.error(e);toast('Gagal membuat PDF')}}
async function sendEmail(){try{toast('Membuat PDF…');const {bytes,data}=await buildPdf();const fd=new FormData();fd.append('pdf',new Blob([bytes],{type:'application/pdf'}),'izin-kerja.pdf');fd.append('data',JSON.stringify(data));const r=await fetch('/api/send-email',{method:'POST',body:fd});const j=await r.json();if(!r.ok)throw new Error(j.message);toast(j.message); if(confirm('Simpan juga ke riwayat admin?')){const sr=await fetch('/api/permits',{method:'POST',body:fd});const sj=await sr.json();if(!sr.ok && sr.message?.includes('Login')) toast('Email terkirim, tetapi riwayat admin belum disimpan (login admin diperlukan).'); else if(sr.ok) toast('Email terkirim dan data tersimpan.');}}catch(e){console.error(e);toast(e.message||'Gagal mengirim email')}}
$('#saveBtn').onclick=downloadPdf;$('#sendBtn').onclick=sendEmail;$('#previewBtn').onclick=async()=>{const {bytes}=await buildPdf();const url=URL.createObjectURL(new Blob([bytes],{type:'application/pdf'}));window.open(url,'_blank')};$('#topBtn').onclick=()=>scrollTo({top:0,behavior:'smooth'});

// --- Admin dashboard ---
const adminModal=$('#adminModal'); const loginBox=$('#loginBox'); const dashboardBox=$('#dashboardBox');
function openAdmin(){adminModal.classList.remove('hidden'); checkAdmin();}
async function checkAdmin(){try{const r=await fetch('/api/auth/me');const j=await r.json();if(j.ok){loginBox.classList.add('hidden');dashboardBox.classList.remove('hidden');loadPermits();}else{loginBox.classList.remove('hidden');dashboardBox.classList.add('hidden');}}catch{}}
$('#adminBtn').onclick=openAdmin; $('#loginCancel').onclick=()=>adminModal.classList.add('hidden');
$('#loginBtn').onclick=async()=>{const r=await fetch('/api/auth/login',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({username:$('#adminUser').value,password:$('#adminPass').value})});const j=await r.json();if(!r.ok)return toast(j.message);toast('Login admin berhasil');checkAdmin();};
$('#logoutBtn').onclick=async()=>{await fetch('/api/auth/logout',{method:'POST'});toast('Logout berhasil');checkAdmin();};
$('#searchPermit').oninput=()=>loadPermits(); $('#statusFilter').onchange=()=>loadPermits();
async function loadPermits(){const q=encodeURIComponent($('#searchPermit').value||'');const st=encodeURIComponent($('#statusFilter').value||'');const r=await fetch(`/api/permits?q=${q}&status=${st}`);if(r.status===401)return checkAdmin();const j=await r.json();const el=$('#permitTable');if(!j.rows?.length){el.innerHTML='<p class="small">Belum ada data tersimpan.</p>';return;}el.innerHTML='<div class="permit-table"><div class="permit-row"><b>Permit</b><b>Pemohon</b><b>Wilayah</b><b>Lokasi</b><b>Status</b><b>Aksi</b></div>'+j.rows.map(x=>`<div class="permit-row"><span>${escapeHtml(x.permitNo)}</span><span>${escapeHtml(x.applicantName)}</span><span>${escapeHtml(x.region)}</span><span>${escapeHtml(x.location)}</span><span><select data-id="${x.id}" class="statusSelect"><option ${x.status==='DRAFT'?'selected':''}>DRAFT</option><option ${x.status==='DIAJUKAN'?'selected':''}>DIAJUKAN</option><option ${x.status==='DISETUJUI'?'selected':''}>DISETUJUI</option><option ${x.status==='DITOLAK'?'selected':''}>DITOLAK</option><option ${x.status==='SELESAI'?'selected':''}>SELESAI</option></select></span><button data-pdf="${x.id}">PDF</button></div>`).join('')+'</div>';el.querySelectorAll('.statusSelect').forEach(s=>s.onchange=async()=>{await fetch(`/api/permits/${s.dataset.id}/status`,{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify({status:s.value})});toast('Status diperbarui');});el.querySelectorAll('[data-pdf]').forEach(b=>b.onclick=()=>window.open(`/api/permits/${b.dataset.pdf}/pdf`,'_blank'));}
function escapeHtml(v){return String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]));}
